"""empty message

Revision ID: 11c91918d9c4
Revises: 668de8d88fd7
Create Date: 2022-05-18 11:20:26.974251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c91918d9c4'
down_revision = '668de8d88fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('todos', 'item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('item', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('todos', 'description')
    # ### end Alembic commands ###
